apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: gcr.io/cto-opus-frictionless-lab-47f9/microservice:1.0.4
        ports:
        - containerPort: 8080
